version: '2'

services:
  vpn:
    image: tsrivishnu/ipsec-vpn-rpi
    restart: always
    env_file:
      - ./vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    volumes:
      - ./opt/src:/opt/src
      - /lib/modules:/lib/modules:ro
    stdin_open: true
    tty: true
    command: ["/opt/src/run.sh"]
